version: '3'
services:
  mysql:
    image: mysql-jp:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: