version: '3.8'
services:
  mysql:
    image: mysql-jp:8.0.21
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - mysql-network
    volumes:
      - mysql-volume:/var/lib/mysql
    
networks:
  default:
    external:
      name: bridge
  mysql-network:
      name: mysql-network

volumes:
  mysql-volume:
    name: mysql-volume
    driver: local