version: "3.0"
services:
  limesurvey:
    build:
      context: fpm/
      dockerfile: Dockerfile
    volumes:
      - /tmp/upload/surveys:/var/www/html/upload/surveys
      - lime-volume:/var/www/html
    links:
      - lime-db
    depends_on:
      - lime-db
    environment:
      - "DB_HOST=mysql-container"
      - "DB_PASSWORD=password"
      - "ADMIN_PASSWORD=password"
  lime-web:
    image: nginx
    links:
      - limesurvey
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - lime-volume:/var/www/html
volumes:
  lime-volume:
    
